apiVersion: v1
kind: Service
metadata:
  name: sys-user
  namespace: {{NAMESPACE}}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sys-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }
