apiVersion: v1
kind: Service
metadata:
  name: eureka-ingress
  namespace: {{NAMESPACE}}
  labels:
    app: eureka-cluster
spec:
  ports:
    - port: 8761
      name: eureka-cluster
  selector:
    app: eureka-cluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-cluster
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: eureka-cluster.nohi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eureka-ingress
                port:
                  number: 8761
status:
  loadBalancer: {}