server:
  port: 8888
spring:
  application:
    name: nohi-web-native
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 日志相关
logging:
  level:
    root: DEBUG
  file:
    path: ${HOME}/tmp/logs

# 定义feign相关配置
feign:
  client:
    config:
      default:
        # 设置feign日志级别
        loggerLevel: full
      # 微服务名称
      cont:
        # 设置feign日志级别
        loggerLevel: full
  httpclient:
    enabled: false
  okhttp:
    enabled: true

management:
  info:
    env:
      # Spring Boot 2.6 后 默认为false
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号

# 业务属性
target:
  url: http://127.0.0.1:8089

config:
  swagger:
    enable: true

biz-config:
  mock:
    enable: true
    dir-path: ${HOME}/tmp/nohi-web
  condition:
    conditioncontroller: true

