POST http://localhost:8099/cont/contDemo
Content-Type: application/json

{
  "head": {
    "trans_seq_no": "f691bb2905f7416190b8223b7d00d92e",
    "request_date": "2020-07-01",
    "request_time": "09:47:34",
    "system_id": "SYSID"
  },
  "body": {
    "htbh": "string"
  }
}

